name: object_serialization
description: An object serialization library for Dart and Flutter that supports circular references and preserves identity.
version: 1.0.1
repository: https://github.com/jgfoster/object_serialization

environment:
  sdk: ^3.3.1

dependencies:
  # none

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
